# Generated by Django 5.2.15 on 2026-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RAZORPAY', 'Razorpay')], default='COD', max_length=20),
        ),
    ]
