# Generated by Django 5.2.15 on 2026-08-23 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_referral_reward_claimed_user_referred_by'),
        ('coupons', '0001_initial'),
        ('orders', '0011_ordercancellationrequest'),
        ('products', '0005_productimage_alt_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_orders_created_at'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', 'created_at'], name='idx_orders_status_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'created_at'], name='idx_orders_paystatus_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'created_at'], name='idx_orders_paymethod_date'),
        ),
        migrations.AddIndex(
            model_name='ordercancellationrequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_cancels_status_date'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='idx_items_order_status'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'status'], name='idx_items_product_status'),
        ),
        migrations.AddIndex(
            model_name='orderreturnrequest',
            index=models.Index(fields=['status', 'refunded_at'], name='idx_returns_status_date'),
        ),
        migrations.AddIndex(
            model_name='orderreturnrequest',
            index=models.Index(fields=['status', 'requested_at'], name='idx_returns_status_reqdate'),
        ),
    ]
