# Generated by Django 5.2.15 on 2026-06-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPVerification',
            new_name='EmailOTP',
        ),
    ]
