# Generated by Django 5.2.15 on 2026-06-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_otpverification_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp_code',
            field=models.CharField(max_length=128),
        ),
    ]
