# Generated by Django 5.2.15 on 2026-07-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
