# Generated by Django 5.2.15 on 2026-07-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_productvariant_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
