# Generated by Django 5.2.15 on 2026-07-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
