# Generated by Django 5.2.15 on 2026-10-03 15:42

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productimage_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                max_length=500, upload_to=apps.products.models.product_image_upload_path
            ),
        ),
    ]
